name: pdf_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_preview: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  flutter_screenutil: ^5.5.3
  flutter_launcher_icons: ^0.11.0
  get_storage: ^2.0.3
  pdf: ^3.4.2
  device_info_plus: ^10.1.2
  syncfusion_flutter_pdfviewer: ^27.2.5
  open_file: ^3.3.2
  flutter_slidable: ^3.0.1
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
